// dl_interceptor injector - ptrace-based .so injection for Android
//
// All .so files are embedded in this binary (via bin2hex).
// On first run, they are extracted to /data/local/tmp/ automatically.
//
// Usage: di_injector -p <package_name> [-a <activity>] [-t <timeout>] [-n]
//
// Requires: root (or shell with ptrace capability)

#include <dirent.h>
#include <dlfcn.h>
#include <elf.h>
#include <errno.h>
#include <fcntl.h>
#include <getopt.h>
#include <inttypes.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/ptrace.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#ifdef __aarch64__
#include <linux/elf.h>
#include <sys/uio.h>

#endif

// Embedded .so data (generated by bin2hex.py at build time)
#include "embedded_interceptor.h"
#include "embedded_nothing.h"
// Only embed GumTrace on aarch64 (or unconditionally based on how we generated
// it)
#include "embedded_gumtrace.h"

#define TAG "di_injector"
#define LOGI(fmt, ...) fprintf(stdout, "[" TAG "] " fmt "\n", ##__VA_ARGS__)
#define LOGE(fmt, ...)                                                         \
  fprintf(stderr, "[" TAG " ERROR] " fmt "\n", ##__VA_ARGS__)

#define DI_EXTRACT_DIR "/data/local/tmp"
#define DI_SO_PATH DI_EXTRACT_DIR "/libdl_interceptor.so"
#define DI_NOTHING_SO_PATH DI_EXTRACT_DIR "/libdl_interceptor_nothing.so"
#define DI_GUMTRACE_SO_PATH DI_EXTRACT_DIR "/libGumTrace.so"

// ---------------------------------------------------------------------------
// Embedded file extraction
// ---------------------------------------------------------------------------

static int write_file(const char *path, const unsigned char *data,
                      unsigned int len) {
  int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
  if (fd < 0) {
    LOGE("open(%s) failed: %s", path, strerror(errno));
    return -1;
  }
  ssize_t written = 0;
  while (written < (ssize_t)len) {
    ssize_t n = write(fd, data + written, len - written);
    if (n < 0) {
      LOGE("write(%s) failed: %s", path, strerror(errno));
      close(fd);
      return -1;
    }
    written += n;
  }
  close(fd);
  return 0;
}

static void set_selinux_context(const char *path) {
  // chcon u:object_r:apk_data_file:s0 <path>
  char cmd[512];
  snprintf(cmd, sizeof(cmd), "chcon u:object_r:apk_data_file:s0 %s 2>/dev/null",
           path);
  system(cmd);
}

static int extract_embedded_files() {
  LOGI("extracting embedded .so files to " DI_EXTRACT_DIR);

  if (write_file(DI_SO_PATH, embedded_interceptor_so,
                 embedded_interceptor_so_len) < 0)
    return -1;
  LOGI("  wrote %s (%u bytes)", DI_SO_PATH, embedded_interceptor_so_len);

  if (write_file(DI_NOTHING_SO_PATH, embedded_nothing_so,
                 embedded_nothing_so_len) < 0)
    return -1;
  LOGI("  wrote %s (%u bytes)", DI_NOTHING_SO_PATH, embedded_nothing_so_len);

  if (write_file(DI_GUMTRACE_SO_PATH, embedded_gumtrace_so,
                 embedded_gumtrace_so_len) < 0)
    return -1;
  LOGI("  wrote %s (%u bytes)", DI_GUMTRACE_SO_PATH, embedded_gumtrace_so_len);

  // Fix SELinux labels so app processes can mmap and write to this directory
  set_selinux_context(DI_SO_PATH);
  set_selinux_context(DI_NOTHING_SO_PATH);
  set_selinux_context(DI_GUMTRACE_SO_PATH);
  // Temporarily set SELinux permissive for dump file creation
  system("setenforce 0 2>/dev/null");

  return 0;
}

// ---------------------------------------------------------------------------
// Register abstraction
// ---------------------------------------------------------------------------

#ifdef __aarch64__

struct regs_t {
  uint64_t regs[31];
  uint64_t sp;
  uint64_t pc;
  uint64_t pstate;
};

static int get_regs(pid_t pid, regs_t *regs) {
  struct iovec iov = {regs, sizeof(*regs)};
  return ptrace(PTRACE_GETREGSET, pid, (void *)NT_PRSTATUS, &iov) == 0 ? 0 : -1;
}

static int set_regs(pid_t pid, const regs_t *regs) {
  struct iovec iov = {(void *)regs, sizeof(*regs)};
  return ptrace(PTRACE_SETREGSET, pid, (void *)NT_PRSTATUS, &iov) == 0 ? 0 : -1;
}

static void regs_set_arg(regs_t *regs, int n, uint64_t val) {
  regs->regs[n] = val;
}
static void regs_set_pc(regs_t *regs, uint64_t pc) { regs->pc = pc; }
static void regs_set_sp(regs_t *regs, uint64_t sp) { regs->sp = sp; }
static void regs_set_ret(regs_t *regs, uint64_t addr) { regs->regs[30] = addr; }
static uint64_t regs_get_ret_val(const regs_t *regs) { return regs->regs[0]; }
static uint64_t regs_get_sp(const regs_t *regs) { return regs->sp; }

#elif defined(__arm__)

#include <asm/ptrace.h>

struct regs_t {
  unsigned long uregs[18];
};

static int get_regs(pid_t pid, regs_t *regs) {
  return ptrace(PTRACE_GETREGS, pid, nullptr, regs) == 0 ? 0 : -1;
}
static int set_regs(pid_t pid, const regs_t *regs) {
  return ptrace(PTRACE_SETREGS, pid, nullptr, regs) == 0 ? 0 : -1;
}
static void regs_set_arg(regs_t *regs, int n, uint64_t val) {
  regs->uregs[n] = (unsigned long)val;
}
static void regs_set_pc(regs_t *regs, uint64_t pc) {
  regs->uregs[15] = (unsigned long)pc;
  if (pc & 1) {
    regs->uregs[16] |= 0x20;
    regs->uregs[15] &= ~1UL;
  } else {
    regs->uregs[16] &= ~0x20;
  }
}
static void regs_set_sp(regs_t *regs, uint64_t sp) {
  regs->uregs[13] = (unsigned long)sp;
}
static void regs_set_ret(regs_t *regs, uint64_t addr) {
  regs->uregs[14] = (unsigned long)addr;
}
static uint64_t regs_get_ret_val(const regs_t *regs) { return regs->uregs[0]; }
static uint64_t regs_get_sp(const regs_t *regs) { return regs->uregs[13]; }

#elif defined(__x86_64__)

#include <sys/user.h>
struct regs_t {
  struct user_regs_struct u;
};

static int get_regs(pid_t pid, regs_t *regs) {
  return ptrace(PTRACE_GETREGS, pid, nullptr, &regs->u) == 0 ? 0 : -1;
}
static int set_regs(pid_t pid, const regs_t *regs) {
  return ptrace(PTRACE_SETREGS, pid, nullptr, &regs->u) == 0 ? 0 : -1;
}
static void regs_set_arg(regs_t *regs, int n, uint64_t val) {
  switch (n) {
  case 0:
    regs->u.rdi = val;
    break;
  case 1:
    regs->u.rsi = val;
    break;
  case 2:
    regs->u.rdx = val;
    break;
  case 3:
    regs->u.r10 = val;
    break;
  case 4:
    regs->u.r8 = val;
    break;
  case 5:
    regs->u.r9 = val;
    break;
  }
}
static void regs_set_pc(regs_t *regs, uint64_t pc) { regs->u.rip = pc; }
static void regs_set_sp(regs_t *regs, uint64_t sp) { regs->u.rsp = sp; }
static void regs_set_ret(regs_t *regs, uint64_t addr) { (void)addr; }
static uint64_t regs_get_ret_val(const regs_t *regs) { return regs->u.rax; }
static uint64_t regs_get_sp(const regs_t *regs) { return regs->u.rsp; }

#elif defined(__i386__)

#include <sys/user.h>
struct regs_t {
  struct user_regs_struct u;
};

static int get_regs(pid_t pid, regs_t *regs) {
  return ptrace(PTRACE_GETREGS, pid, nullptr, &regs->u) == 0 ? 0 : -1;
}
static int set_regs(pid_t pid, const regs_t *regs) {
  return ptrace(PTRACE_SETREGS, pid, nullptr, &regs->u) == 0 ? 0 : -1;
}
static void regs_set_arg(regs_t *regs, int n, uint64_t val) {
  (void)regs;
  (void)n;
  (void)val;
}
static void regs_set_pc(regs_t *regs, uint64_t pc) { regs->u.eip = (long)pc; }
static void regs_set_sp(regs_t *regs, uint64_t sp) { regs->u.esp = (long)sp; }
static void regs_set_ret(regs_t *regs, uint64_t addr) { (void)addr; }
static uint64_t regs_get_ret_val(const regs_t *regs) { return regs->u.eax; }
static uint64_t regs_get_sp(const regs_t *regs) { return regs->u.esp; }

#else
#error "Unsupported architecture"
#endif

// ---------------------------------------------------------------------------
// ptrace memory read/write
// ---------------------------------------------------------------------------

static int ptrace_read(pid_t pid, uintptr_t addr, void *buf, size_t len) {
  size_t i = 0;
  auto *dst = (uint8_t *)buf;
  for (; i + sizeof(long) <= len; i += sizeof(long)) {
    errno = 0;
    long val = ptrace(PTRACE_PEEKDATA, pid, (void *)(addr + i), nullptr);
    if (errno)
      return -1;
    memcpy(dst + i, &val, sizeof(long));
  }
  if (i < len) {
    errno = 0;
    long val = ptrace(PTRACE_PEEKDATA, pid, (void *)(addr + i), nullptr);
    if (errno)
      return -1;
    memcpy(dst + i, &val, len - i);
  }
  return 0;
}

static int ptrace_write(pid_t pid, uintptr_t addr, const void *buf,
                        size_t len) {
  size_t i = 0;
  auto *src = (const uint8_t *)buf;
  for (; i + sizeof(long) <= len; i += sizeof(long)) {
    long val;
    memcpy(&val, src + i, sizeof(long));
    if (ptrace(PTRACE_POKEDATA, pid, (void *)(addr + i), (void *)val) < 0)
      return -1;
  }
  if (i < len) {
    errno = 0;
    long val = ptrace(PTRACE_PEEKDATA, pid, (void *)(addr + i), nullptr);
    if (errno)
      return -1;
    memcpy(&val, src + i, len - i);
    if (ptrace(PTRACE_POKEDATA, pid, (void *)(addr + i), (void *)val) < 0)
      return -1;
  }
  return 0;
}

// ---------------------------------------------------------------------------
// /proc maps helpers
// ---------------------------------------------------------------------------

static uintptr_t get_module_base(pid_t pid, const char *module_name) {
  char path[256];
  snprintf(path, sizeof(path), "/proc/%d/maps", pid);
  FILE *fp = fopen(path, "r");
  if (!fp)
    return 0;
  char line[512];
  uintptr_t base = 0;
  while (fgets(line, sizeof(line), fp)) {
    if (strstr(line, module_name) && strstr(line, "r-xp")) {
      sscanf(line, "%" SCNxPTR, &base);
      break;
    }
    if (base == 0 && strstr(line, module_name) && strstr(line, "r--p"))
      sscanf(line, "%" SCNxPTR, &base);
  }
  fclose(fp);
  return base;
}

static uintptr_t get_remote_func_addr(pid_t pid, const char *lib_name,
                                      void *local_func) {
  uintptr_t local_base = get_module_base(getpid(), lib_name);
  uintptr_t remote_base = get_module_base(pid, lib_name);
  if (!local_base || !remote_base)
    return 0;
  return remote_base + ((uintptr_t)local_func - local_base);
}

// ---------------------------------------------------------------------------
// Remote function call via ptrace
// ---------------------------------------------------------------------------

static int ptrace_continue_and_wait(pid_t pid) {
  if (ptrace(PTRACE_CONT, pid, nullptr, nullptr) < 0) {
    LOGE("PTRACE_CONT failed: %s", strerror(errno));
    return -1;
  }
  int status = 0;
  if (waitpid(pid, &status, 0) < 0) {
    LOGE("waitpid failed: %s", strerror(errno));
    return -1;
  }
  if (WIFSTOPPED(status) && WSTOPSIG(status) == SIGSEGV)
    return 0;
  if (WIFSTOPPED(status)) {
    LOGI("stopped by signal %d", WSTOPSIG(status));
    return 0;
  }
  LOGE("unexpected wait status: 0x%x", status);
  return -1;
}

static uint64_t ptrace_call(pid_t pid, uintptr_t func_addr, uint64_t *args,
                            int nargs) {
  regs_t regs, saved;
  if (get_regs(pid, &regs) < 0) {
    LOGE("get_regs failed: %s", strerror(errno));
    return (uint64_t)-1;
  }
  memcpy(&saved, &regs, sizeof(regs));

#if defined(__aarch64__) || defined(__arm__)
  for (int i = 0; i < nargs && i < 8; i++)
    regs_set_arg(&regs, i, args[i]);
  regs_set_pc(&regs, func_addr);
  regs_set_ret(&regs, 0);
#elif defined(__x86_64__)
  for (int i = 0; i < nargs && i < 6; i++)
    regs_set_arg(&regs, i, args[i]);
  uint64_t sp = regs_get_sp(&regs) - 8;
  uint64_t zero = 0;
  ptrace_write(pid, sp, &zero, 8);
  regs_set_sp(&regs, sp);
  regs_set_pc(&regs, func_addr);
#elif defined(__i386__)
  uint64_t sp = regs_get_sp(&regs);
  for (int i = nargs - 1; i >= 0; i--) {
    sp -= 4;
    uint32_t v = (uint32_t)args[i];
    ptrace_write(pid, sp, &v, 4);
  }
  sp -= 4;
  uint32_t zero = 0;
  ptrace_write(pid, sp, &zero, 4);
  regs_set_sp(&regs, sp);
  regs_set_pc(&regs, func_addr);
#endif

  if (set_regs(pid, &regs) < 0) {
    LOGE("set_regs failed");
    return (uint64_t)-1;
  }
  if (ptrace_continue_and_wait(pid) < 0) {
    set_regs(pid, &saved);
    return (uint64_t)-1;
  }

  regs_t result;
  get_regs(pid, &result);
  uint64_t ret = regs_get_ret_val(&result);
  set_regs(pid, &saved);
  return ret;
}

// ---------------------------------------------------------------------------
// Process helpers
// ---------------------------------------------------------------------------

static pid_t find_pid_by_name(const char *pkg_name) {
  DIR *dir = opendir("/proc");
  if (!dir)
    return -1;
  struct dirent *entry;
  while ((entry = readdir(dir)) != nullptr) {
    if (entry->d_type != DT_DIR)
      continue;
    char *end;
    long pid = strtol(entry->d_name, &end, 10);
    if (*end != '\0' || pid <= 0)
      continue;
    char path[256];
    snprintf(path, sizeof(path), "/proc/%ld/cmdline", pid);
    FILE *fp = fopen(path, "r");
    if (!fp)
      continue;
    char cmdline[256] = {};
    fread(cmdline, 1, sizeof(cmdline) - 1, fp);
    fclose(fp);
    if (strcmp(cmdline, pkg_name) == 0) {
      closedir(dir);
      return (pid_t)pid;
    }
  }
  closedir(dir);
  return -1;
}

static pid_t wait_for_process(const char *pkg_name, int timeout_ms) {
  int elapsed = 0;
  const int interval_ms = 5;
  while (elapsed < timeout_ms) {
    pid_t pid = find_pid_by_name(pkg_name);
    if (pid > 0)
      return pid;
    usleep(interval_ms * 1000);
    elapsed += interval_ms;
  }
  return -1;
}

static int start_app(const char *pkg_name, const char *activity) {
  char cmd[512];
  if (activity) {
    snprintf(cmd, sizeof(cmd), "am start -n %s/%s", pkg_name, activity);
  } else {
    char resolve_cmd[256];
    snprintf(resolve_cmd, sizeof(resolve_cmd),
             "cmd package resolve-activity --brief -c "
             "android.intent.category.LAUNCHER %s 2>/dev/null | tail -1",
             pkg_name);
    FILE *fp = popen(resolve_cmd, "r");
    if (fp) {
      char component[256] = {};
      if (fgets(component, sizeof(component), fp)) {
        size_t len = strlen(component);
        while (len > 0 &&
               (component[len - 1] == '\n' || component[len - 1] == '\r'))
          component[--len] = '\0';
        pclose(fp);
        if (len > 0 && strchr(component, '/')) {
          snprintf(cmd, sizeof(cmd), "am start -n %s", component);
          LOGI("starting app: %s", cmd);
          return system(cmd);
        }
      } else {
        pclose(fp);
      }
    }
    snprintf(
        cmd, sizeof(cmd),
        "monkey -p %s -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1",
        pkg_name);
  }
  LOGI("starting app: %s", cmd);
  return system(cmd);
}

static void force_stop_app(const char *pkg_name) {
  char cmd[256];
  snprintf(cmd, sizeof(cmd), "am force-stop %s", pkg_name);
  system(cmd);
  usleep(500 * 1000);
}

// ---------------------------------------------------------------------------
// Breakpoint spec parsing
// ---------------------------------------------------------------------------

#define MAX_BREAKPOINTS 32

struct bp_spec {
  char lib_name[128];
  int index; // -1 = all
};

static int parse_bp_spec(const char *str, bp_spec *out) {
  // Format: "libfoo.so:N" or "libfoo.so" (all entries) or "libfoo.so:*"
  const char *colon = strchr(str, ':');
  if (!colon) {
    // No colon: break on all entries
    strncpy(out->lib_name, str, sizeof(out->lib_name) - 1);
    out->lib_name[sizeof(out->lib_name) - 1] = '\0';
    out->index = -1;
    return 0;
  }
  size_t name_len = (size_t)(colon - str);
  if (name_len >= sizeof(out->lib_name))
    name_len = sizeof(out->lib_name) - 1;
  memcpy(out->lib_name, str, name_len);
  out->lib_name[name_len] = '\0';

  const char *idx_str = colon + 1;
  if (strcmp(idx_str, "*") == 0) {
    out->index = -1;
  } else {
    out->index = atoi(idx_str);
  }
  return 0;
}

// ---------------------------------------------------------------------------
// Core injection
// ---------------------------------------------------------------------------

static int do_inject(pid_t pid, const char *so_path, const char *pkg_name,
                     bp_spec *breakpoints, int num_bp, bp_spec *dumppoints,
                     int num_dp, bp_spec *hookpoints, int num_hk,
                     bp_spec *tracepoints, int num_tr) {
  LOGI("attaching to pid %d", pid);
  if (ptrace(PTRACE_ATTACH, pid, nullptr, nullptr) < 0) {
    LOGE("PTRACE_ATTACH failed: %s", strerror(errno));
    return -1;
  }
  int status;
  if (waitpid(pid, &status, 0) < 0) {
    LOGE("waitpid after attach failed: %s", strerror(errno));
    ptrace(PTRACE_DETACH, pid, nullptr, nullptr);
    return -1;
  }
  LOGI("attached, process stopped");

  const char *libc_name = "libc.so";
  const char *libdl_name = "libdl.so";

  uintptr_t remote_mmap = get_remote_func_addr(pid, libc_name, (void *)mmap);
  uintptr_t remote_munmap =
      get_remote_func_addr(pid, libc_name, (void *)munmap);
  uintptr_t remote_dlopen =
      get_remote_func_addr(pid, libdl_name, (void *)dlopen);
  uintptr_t remote_dlsym = get_remote_func_addr(pid, libdl_name, (void *)dlsym);
  uintptr_t remote_dlerror =
      get_remote_func_addr(pid, libdl_name, (void *)dlerror);

  if (!remote_mmap || !remote_dlopen || !remote_dlsym) {
    LOGE("failed to resolve remote functions (mmap=%p, dlopen=%p, dlsym=%p)",
         (void *)remote_mmap, (void *)remote_dlopen, (void *)remote_dlsym);
    ptrace(PTRACE_DETACH, pid, nullptr, nullptr);
    return -1;
  }

  LOGI("remote mmap=%p dlopen=%p dlsym=%p", (void *)remote_mmap,
       (void *)remote_dlopen, (void *)remote_dlsym);

  // mmap a page in target
  size_t alloc_size = 0x1000;
  uint64_t mmap_args[6] = {0,
                           alloc_size,
                           PROT_READ | PROT_WRITE,
                           MAP_PRIVATE | MAP_ANONYMOUS,
                           (uint64_t)-1,
                           0};
  uint64_t remote_buf = ptrace_call(pid, remote_mmap, mmap_args, 6);
  if (remote_buf == (uint64_t)-1 || remote_buf == (uint64_t)MAP_FAILED) {
    LOGE("remote mmap failed");
    ptrace(PTRACE_DETACH, pid, nullptr, nullptr);
    return -1;
  }

  // dlopen
  size_t path_len = strlen(so_path) + 1;
  ptrace_write(pid, (uintptr_t)remote_buf, so_path, path_len);
  uint64_t dlopen_args[2] = {remote_buf, RTLD_NOW};
  LOGI("calling dlopen(\"%s\") in target", so_path);
  uint64_t handle = ptrace_call(pid, remote_dlopen, dlopen_args, 2);

  if (handle == 0) {
    LOGE("dlopen returned NULL");
    if (remote_dlerror) {
      uint64_t no_args[1] = {0};
      uint64_t err_ptr = ptrace_call(pid, remote_dlerror, no_args, 0);
      if (err_ptr) {
        char msg[256] = {};
        ptrace_read(pid, (uintptr_t)err_ptr, msg, 255);
        LOGE("dlerror: %s", msg);
      }
    }
    uint64_t munmap_args[2] = {remote_buf, alloc_size};
    ptrace_call(pid, remote_munmap, munmap_args, 2);
    ptrace(PTRACE_DETACH, pid, nullptr, nullptr);
    return -1;
  }
  LOGI("dlopen succeeded, handle=%p", (void *)handle);

  // Helper lambda: dlsym a symbol from the injected .so
  auto remote_resolve = [&](const char *sym_name) -> uint64_t {
    ptrace_write(pid, (uintptr_t)remote_buf, sym_name, strlen(sym_name) + 1);
    uint64_t dlsym_args[2] = {handle, remote_buf};
    return ptrace_call(pid, remote_dlsym, dlsym_args, 2);
  };

  // Call dl_interceptor_init()
  uint64_t init_addr = remote_resolve("dl_interceptor_init");
  if (init_addr == 0) {
    LOGE("dlsym(\"dl_interceptor_init\") returned NULL");
  } else {
    LOGI("calling dl_interceptor_init() at %p", (void *)init_addr);
    uint64_t no_args[1] = {0};
    uint64_t ret = ptrace_call(pid, (uintptr_t)init_addr, no_args, 0);
    if (ret == 0)
      LOGI("dl_interceptor_init() succeeded");
    else
      LOGE("dl_interceptor_init() returned %d", (int)(int64_t)ret);
  }

  // Set package name in lib
  if (pkg_name) {
    uint64_t set_pkg_addr = remote_resolve("dl_interceptor_set_package_name");
    if (set_pkg_addr != 0) {
      ptrace_write(pid, (uintptr_t)remote_buf, pkg_name, strlen(pkg_name) + 1);
      uint64_t pkg_args[1] = {remote_buf};
      ptrace_call(pid, (uintptr_t)set_pkg_addr, pkg_args, 1);
    }
  }

  // Set breakpoints if any
  if (num_bp > 0) {
    uint64_t bp_func = remote_resolve("dl_interceptor_set_breakpoint");
    if (bp_func == 0) {
      LOGE("dlsym(\"dl_interceptor_set_breakpoint\") returned NULL");
    } else {
      for (int i = 0; i < num_bp; i++) {
        ptrace_write(pid, (uintptr_t)remote_buf, breakpoints[i].lib_name,
                     strlen(breakpoints[i].lib_name) + 1);
        uint64_t bp_args[2] = {remote_buf,
                               (uint64_t)(int64_t)breakpoints[i].index};
        LOGI("setting breakpoint: %s:%d", breakpoints[i].lib_name,
             breakpoints[i].index);
        uint64_t ret = ptrace_call(pid, (uintptr_t)bp_func, bp_args, 2);
        if (ret == 0)
          LOGI("breakpoint set OK");
        else
          LOGE("breakpoint set failed (ret=%d)", (int)(int64_t)ret);
      }
    }
  }

  // Set dumppoints if any
  if (num_dp > 0) {
    uint64_t dp_func = remote_resolve("dl_interceptor_set_dumppoint");
    if (dp_func == 0) {
      LOGE("dlsym(\"dl_interceptor_set_dumppoint\") returned NULL");
    } else {
      for (int i = 0; i < num_dp; i++) {
        ptrace_write(pid, (uintptr_t)remote_buf, dumppoints[i].lib_name,
                     strlen(dumppoints[i].lib_name) + 1);
        uint64_t dp_args[2] = {remote_buf,
                               (uint64_t)(int64_t)dumppoints[i].index};
        LOGI("setting dumppoint: %s:%d", dumppoints[i].lib_name,
             dumppoints[i].index);
        uint64_t ret = ptrace_call(pid, (uintptr_t)dp_func, dp_args, 2);
        if (ret == 0)
          LOGI("dumppoint set OK");
        else
          LOGE("dumppoint set failed (ret=%d)", (int)(int64_t)ret);
      }
    }
  }

  // Set hookpoints if any
  if (num_hk > 0) {
    uint64_t hk_func = remote_resolve("dl_interceptor_set_hookpoint");
    if (hk_func == 0) {
      LOGE("dlsym(\"dl_interceptor_set_hookpoint\") returned NULL");
    } else {
      for (int i = 0; i < num_hk; i++) {
        ptrace_write(pid, (uintptr_t)remote_buf, hookpoints[i].lib_name,
                     strlen(hookpoints[i].lib_name) + 1);
        uint64_t hk_args[1] = {remote_buf};
        LOGI("setting hookpoint: %s", hookpoints[i].lib_name);
        uint64_t ret = ptrace_call(pid, (uintptr_t)hk_func, hk_args, 1);
        if (ret == 0)
          LOGI("hookpoint set OK");
        else
          LOGE("hookpoint set failed (ret=%d)", (int)(int64_t)ret);
      }
    }
  }

  // Set tracepoints if any
  if (num_tr > 0) {
    uint64_t tr_func = remote_resolve("dl_interceptor_set_tracepoint");
    if (tr_func == 0) {
      LOGE("dlsym(\"dl_interceptor_set_tracepoint\") returned NULL");
    } else {
      for (int i = 0; i < num_tr; i++) {
        ptrace_write(pid, (uintptr_t)remote_buf, tracepoints[i].lib_name,
                     strlen(tracepoints[i].lib_name) + 1);
        uint64_t tr_args[2] = {remote_buf,
                               (uint64_t)(int64_t)tracepoints[i].index};
        LOGI("setting tracepoint: %s:%d", tracepoints[i].lib_name,
             tracepoints[i].index);
        uint64_t ret = ptrace_call(pid, (uintptr_t)tr_func, tr_args, 2);
        if (ret == 0)
          LOGI("tracepoint set OK");
        else
          LOGE("tracepoint set failed (ret=%d)", (int)(int64_t)ret);
      }
    }
  }

  // Cleanup
  uint64_t munmap_args[2] = {remote_buf, alloc_size};
  ptrace_call(pid, remote_munmap, munmap_args, 2);
  ptrace(PTRACE_DETACH, pid, nullptr, nullptr);
  LOGI("detached from pid %d", pid);
  return handle ? 0 : -1;
}

// ---------------------------------------------------------------------------
// Usage / main
// ---------------------------------------------------------------------------

static void usage(const char *prog) {
  fprintf(
      stderr,
      "dl_interceptor injector - ptrace-based .so injection for Android\n"
      "\n"
      "All required .so files are embedded in this binary and extracted "
      "automatically.\n"
      "\n"
      "Usage: %s [options]\n"
      "\n"
      "Required:\n"
      "  -p <package>    Target app package name (e.g. com.example.app)\n"
      "\n"
      "Optional:\n"
      "  -b <lib:N>      Breakpoint on init_array entry (1-based, can repeat)\n"
      "                  Format: libname.so:N | libname.so:* | libname.so\n"
      "                  Process SIGSTOP before the Nth init function.\n"
      "  -d <lib:N>      Dump .so memory at init_array entry (1-based, can "
      "repeat)\n"
      "                  Dumps to /data/local/tmp/<lib>_dump_<N>.so\n"
      "                  Captures relocated code before/at the Nth init "
      "function.\n"
      "  -hk <lib>       Hook all init_array functions of a specific lib and "
      "trace execution\n"
      "                  Format: libname.so | all (to hook all libraries)\n"
      "  -t <lib:N>      Trace a specific init_array execution using GumTrace "
      "(1-based, can repeat)\n"
      "                  Format: libname.so:N | libname.so:* | libname.so\n"
      "  -a <activity>   Activity to launch (default: auto-detect)\n"
      "  -w <timeout>    Timeout in ms for process spawn (default: 10000)\n"
      "  -n              Don't start app, inject into running process\n"
      "  -h              Show this help\n"
      "\n"
      "Example:\n"
      "  %s -p com.example.app\n"
      "  %s -p com.example.app -b libfk.so:1\n"
      "  %s -p com.example.app -d libfk.so:1\n"
      "  %s -p com.example.app -hk libfk.so\n"
      "  %s -p com.example.app -hk all\n"
      "\n"
      "Notes:\n"
      "  - Requires root or shell with ptrace capability\n"
      "  - Index is 1-based (1 = first init_array entry)\n"
      "  - .so files are extracted to " DI_EXTRACT_DIR " on each run\n",
      prog, prog, prog, prog, prog, prog);
}

int main(int argc, char *argv[]) {
  const char *pkg_name = nullptr;
  const char *activity = nullptr;
  int timeout_ms = 10000;
  bool no_start = false;
  bp_spec breakpoints[MAX_BREAKPOINTS];
  bp_spec dumppoints[MAX_BREAKPOINTS];
  bp_spec hookpoints[MAX_BREAKPOINTS];
  bp_spec tracepoints[MAX_BREAKPOINTS];
  int num_bp = 0;
  int num_dp = 0;
  int num_hk = 0;
  int num_tr = 0;

  // Support -hk by replacing it with -k before parsing
  for (int i = 1; i < argc; i++) {
    if (strcmp(argv[i], "-hk") == 0) {
      argv[i] = (char *)"-k";
    }
  }

  int opt;
  while ((opt = getopt(argc, argv, "p:a:w:t:b:d:k:nh")) != -1) {
    switch (opt) {
    case 'p':
      pkg_name = optarg;
      break;
    case 'a':
      activity = optarg;
      break;
    case 'w':
      timeout_ms = atoi(optarg);
      break;
    case 't':
      if (num_tr >= MAX_BREAKPOINTS) {
        LOGE("too many tracepoints");
        return 1;
      }
      parse_bp_spec(optarg, &tracepoints[num_tr++]);
      break;
    case 'b':
      if (num_bp >= MAX_BREAKPOINTS) {
        LOGE("too many breakpoints");
        return 1;
      }
      parse_bp_spec(optarg, &breakpoints[num_bp++]);
      break;
    case 'd':
      if (num_dp >= MAX_BREAKPOINTS) {
        LOGE("too many dumppoints");
        return 1;
      }
      parse_bp_spec(optarg, &dumppoints[num_dp++]);
      break;
    case 'k':
      if (num_hk >= MAX_BREAKPOINTS) {
        LOGE("too many hookpoints");
        return 1;
      }
      parse_bp_spec(optarg, &hookpoints[num_hk++]);
      break;
    case 'n':
      no_start = true;
      break;
    case 'h':
      usage(argv[0]);
      return 0;
    default:
      usage(argv[0]);
      return 1;
    }
  }

  if (!pkg_name) {
    LOGE("package name is required (-p)");
    usage(argv[0]);
    return 1;
  }

  if (extract_embedded_files() < 0) {
    LOGE("failed to extract embedded files");
    return 1;
  }

  pid_t pid;
  if (no_start) {
    pid = find_pid_by_name(pkg_name);
    if (pid < 0) {
      LOGE("process not found: %s", pkg_name);
      return 1;
    }
    LOGI("found running process: %s (pid=%d)", pkg_name, pid);
  } else {
    LOGI("force stopping %s", pkg_name);
    force_stop_app(pkg_name);
    LOGI("starting %s", pkg_name);
    if (start_app(pkg_name, activity) != 0) {
      LOGE("failed to start app");
      return 1;
    }
    LOGI("waiting for process (timeout=%dms)...", timeout_ms);
    pid = wait_for_process(pkg_name, timeout_ms);
    if (pid < 0) {
      LOGE("timeout: %s did not appear within %dms", pkg_name, timeout_ms);
      return 1;
    }
    LOGI("process found: pid=%d", pid);
  }

  int ret =
      do_inject(pid, DI_SO_PATH, pkg_name, breakpoints, num_bp, dumppoints,
                num_dp, hookpoints, num_hk, tracepoints, num_tr);
  if (ret == 0) {
    LOGI("injection successful!");
    if (num_bp > 0) {
      LOGI("breakpoints active - process will SIGSTOP when hit");
      LOGI("resume with: kill -CONT %d", pid);
    }
    if (num_dp > 0) {
      LOGI("dumppoints active - .so will be dumped to " DI_EXTRACT_DIR);
      LOGI("NOTE: SELinux set to permissive for dump. Restore with: setenforce "
           "1");
    }
    if (num_hk > 0) {
      LOGI("hookpoints active - tracing all init_array entries for the "
           "specified libs");
    }
    if (num_tr > 0) {
      LOGI("tracepoints active - tracing specific init_array execution using "
           "GumTrace");
    }
  } else {
    LOGE("injection failed");
  }
  return ret;
}
